{% set version = '0.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ufs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ufs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ufs/ufs_{{ version }}.tar.gz
  sha256: d45402a04b19a4313a12996c7a8c8eb2e00d5c91209dc0f1c1b2c6cde2fd2a1d

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggally >=1.4.0
    - r-suppdists >=1.1.9
    - r-digest >=0.6.19
    - r-diptest >=0.75.7
    - r-dplyr >=0.7.6
    - r-ggplot2 >=2.2.1
    - r-ggrepel >=0.8
    - r-ggridges >=0.5.0
    - r-gridextra >=2.3
    - r-gtable >=0.2.0
    - r-knitr >=1.22
    - r-pander >=0.6.3
    - r-plyr >=1.8.4
    - r-scales >=1.0.0
    - r-viridis >=0.5.1
  run:
    - r-base
    - r-ggally >=1.4.0
    - r-suppdists >=1.1.9
    - r-digest >=0.6.19
    - r-diptest >=0.75.7
    - r-dplyr >=0.7.6
    - r-ggplot2 >=2.2.1
    - r-ggrepel >=0.8
    - r-ggridges >=0.5.0
    - r-gridextra >=2.3
    - r-gtable >=0.2.0
    - r-knitr >=1.22
    - r-pander >=0.6.3
    - r-plyr >=1.8.4
    - r-scales >=1.0.0
    - r-viridis >=0.5.1

test:
  commands:
    - $R -e "library('ufs')"           # [not win]
    - "\"%R%\" -e \"library('ufs')\""  # [win]

about:
  home: https://r-packages.gitlab.io/ufs
  license: GPL-3
  summary: This is a new version of the 'userfriendlyscience' package, which has grown a bit
    unwieldy. Therefore, distinct functionalities are being 'consciously uncoupled'
    into different packages. This package contains the general-purpose tools and utilities
    (see the 'behaviorchange' package, the 'rosetta' package, and the soon-to-be-released
    'scd' package for other functionality), and is the most direct 'successor' of the
    original 'userfriendlyscience' package. For example, this package contains a number
    of basic functions to create higher level plots, such as diamond plots, to easily
    plot sampling distributions, to generate confidence intervals, to plan study sample
    sizes for confidence intervals, and to do some basic operations such as (dis)attenuate
    effect size estimates.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ufs
# Type: Package
# Title: Quantitative Analysis Made Accessible
# Version: 0.3.1
# Date: 2019-8-22
# Authors@R: person(given = "Gjalt-Jorn", family = "Peters", role = c("aut", "cre"), email = "gjalt-jorn@userfriendlyscience.com", comment = c(ORCID = "0000-0002-0336-9589"))
# Maintainer: Gjalt-Jorn Peters <gjalt-jorn@userfriendlyscience.com>
# License: GPL (>= 3)
# Description: This is a new version of the 'userfriendlyscience' package, which has grown a bit unwieldy. Therefore, distinct functionalities are being 'consciously uncoupled' into different packages. This package contains the general-purpose tools and utilities (see the 'behaviorchange' package, the 'rosetta' package, and the soon-to-be-released 'scd' package for other functionality), and is the most direct 'successor' of the original 'userfriendlyscience' package. For example, this package contains a number of basic functions to create higher level plots, such as diamond plots, to easily plot sampling distributions, to generate confidence intervals, to plan study sample sizes for confidence intervals, and to do some basic operations such as (dis)attenuate effect size estimates.
# URL: https://r-packages.gitlab.io/ufs
# BugReports: https://gitlab.com/r-packages/ufs/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: R (>= 3.0.0)
# Suggests: bootES (>= 1.2), lavaan (>= 0.6), MBESS (>= 4.5.1), psych (>= 1.8), rio (>= 0.5), rmarkdown
# Imports: digest (>= 0.6.19), diptest (>= 0.75.7), dplyr (>= 0.7.6), GGally (>= 1.4.0), ggplot2 (>= 2.2.1), ggrepel (>= 0.8), ggridges (>= 0.5.0), grDevices (>= 3.0.0), gridExtra (>= 2.3), gtable (>= 0.2.0), knitr (>= 1.22), pander (>= 0.6.3), plyr (>= 1.8.4), scales (>= 1.0.0), SuppDists (>= 1.1.9), viridis (>= 0.5.1)
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-08-22 15:15:19 UTC; gjalt
# Author: Gjalt-Jorn Peters [aut, cre] (<https://orcid.org/0000-0002-0336-9589>)
# Repository: CRAN
# Date/Publication: 2019-08-22 17:30:02 UTC
