{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ufs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ufs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ufs/ufs_{{ version }}.tar.gz
  sha256: 98b4b044eee7dc97994cfd1d17945d4a6ec38edd7de6b51396a6df291d41870b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggally >=1.4.0
    - r-suppdists >=1.1.9
    - r-digest >=0.6.19
    - r-diptest >=0.75.7
    - r-dplyr >=0.7.6
    - r-ggplot2 >=2.2.1
    - r-ggrepel >=0.8
    - r-ggridges >=0.5.0
    - r-gridextra >=2.3
    - r-gtable >=0.2.0
    - r-knitr >=1.22
    - r-pander >=0.6.3
    - r-plyr >=1.8.4
    - r-scales >=1.0.0
    - r-viridis >=0.5.1
  run:
    - r-base
    - r-ggally >=1.4.0
    - r-suppdists >=1.1.9
    - r-digest >=0.6.19
    - r-diptest >=0.75.7
    - r-dplyr >=0.7.6
    - r-ggplot2 >=2.2.1
    - r-ggrepel >=0.8
    - r-ggridges >=0.5.0
    - r-gridextra >=2.3
    - r-gtable >=0.2.0
    - r-knitr >=1.22
    - r-pander >=0.6.3
    - r-plyr >=1.8.4
    - r-scales >=1.0.0
    - r-viridis >=0.5.1

test:
  commands:
    - $R -e "library('ufs')"           # [not win]
    - "\"%R%\" -e \"library('ufs')\""  # [win]

about:
  home: https://ufs.opens.science
  license: GPL (>= 3)
  summary: This is a new version of the 'userfriendlyscience' package, which has grown a bit
    unwieldy. Therefore, distinct functionalities are being 'consciously uncoupled'
    into different packages. This package contains the general-purpose tools and utilities
    (see the 'behaviorchange' and the 'rosetta' packages for other functionality), and
    is the most direct 'successor' of the original 'userfriendlyscience' package. For
    example, this package contains a number of basic functions to create higher level
    plots, such as diamond plots, to easily plot sampling distributions, to generate
    confidence intervals, to plan study sample sizes for confidence intervals, and to
    do some basic operations such as (dis)attenuate effect size estimates.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ufs
# Type: Package
# Title: Quantitative Analysis Made Accessible
# Version: 0.2.0
# Date: 2019-02-11
# Authors@R: c(person("Gjalt-Jorn", "Peters", email = "gjalt-jorn@userfriendlyscience.com", role = c("aut", "cre", "ctb")))
# Maintainer: Gjalt-Jorn Peters <gjalt-jorn@userfriendlyscience.com>
# License: GPL (>= 3)
# Description: This is a new version of the 'userfriendlyscience' package, which has grown a bit unwieldy. Therefore, distinct functionalities are being 'consciously uncoupled' into different packages. This package contains the general-purpose tools and utilities (see the 'behaviorchange' and the 'rosetta' packages for other functionality), and is the most direct 'successor' of the original 'userfriendlyscience' package. For example, this package contains a number of basic functions to create higher level plots, such as diamond plots, to easily plot sampling distributions, to generate confidence intervals, to plan study sample sizes for confidence intervals, and to do some basic operations such as (dis)attenuate effect size estimates.
# URL: https://ufs.opens.science
# BugReports: https://github.com/matherion/ufs/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: R (>= 3.0.0)
# Suggests: psych (>= 1.8.4), rio (>= 0.5.10)
# Imports: BiasedUrn (>= 1.07), dplyr (>= 0.7.6), ggplot2 (>= 2.2.1), ggridges (>= 0.5.0), grDevices (>= 3.5.1), grid (>= 3.5.1), gtable (>= 0.2.0), pander (>= 0.6.3), scales (>= 1.0.0), SuppDists (>= 1.1.9), viridis (>= 0.5.1)
# NeedsCompilation: no
# Packaged: 2019-02-12 10:34:20 UTC; micro
# Author: Gjalt-Jorn Peters [aut, cre, ctb]
# Repository: CRAN
# Date/Publication: 2019-02-12 13:10:03 UTC
