appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OXL7nXpwIPwpPPE5sgkoVLtl/U4C9/198JIWii4JzIcJ95XBYNOITtZfBVB6rIqfiVaiXoeqtK+g4oHdet0jwStj/ux6tsBrxru3KxJq2S8zFKGabrY6CSrXWXj5JFJobFi5Xi41bkn4j4cgUucifg3Xs5vtNElJBq67PmYWXpnKYwouAYtG3dpOJNe487vRo+cSfb1GKzENzWIidWOmQwL5kAdemMcWjadF4GemzvSQxhwdWwh78bpNmJeIExpRbv6vxux0A4khArvdFjtkNoGfu45p9DP2RTr0JnKhzDefhlxID79xBuaKKRT7erApLBwgcNZVOHShHj9MDGZ+1F4s6vZcTDmiU3Wudg5xwa/MUJHMpy6z2ahl6DrsoPZKXG6HlcnBHVKBSAtfmUhtLFCRqZAqnfqPUITqs5eRd+63nL8IvN5gJUcV4WqLEojowbr5FC9QgZTNhO1GJ0NSjMN3AUlRDQsaCA8t15ikbCVy3QmViJ3MhHrLLK49tNEyVyk5Ufsf0XS7SeQ6AWfgHKn6mqY+XeraQVX8yr3T/hyTIgtKzuGOD+xX8YPUSDnN2g34wrMxmEuQ92RCv9IvAW7UQjMqRJ4i3uDBdHmT87js+NTq963x4iWjgIAPS8txClncew4yxERdkCAhW7BYghvEEpm3B7xm0L6auWyf3gI=}
